---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/10/2019 02:40
---

---@class RageUI
RageUI = {}

---@class UIMenu
UIMenu = {}

---@class Item
RageUI.Item = {}

---@class Panel
RageUI.Panel = {}

---@class Window
RageUI.Window = {}

---@class Panels
Panels = {}

setmetatable({}, {__index = Panels})

---@class Items
Items = {}

setmetatable({}, {__index = Items})

